# Docker Compose 配置
version: '3.8'

services:
  # Streamlit 前端服务
  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:5000
      - JWT_SECRET=production-secret-key
    depends_on:
      - backend
    restart: unless-stopped

  # FastAPI 后端服务
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://user:password@db:5432/classcheckin
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=production-secret-key
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # PostgreSQL 数据库
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=classcheckin
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
